In [3]:
import numpy as np

In [8]:
a = np.random.randn(5, 1)

In [9]:
print(a)

[[ 0.89814481]
 [ 0.87892505]
 [-1.78306677]
 [ 1.11113131]
 [ 0.60916656]]


In [13]:
print(a.shape)

(5, 1)


In [10]:
print(a.T)

[[ 0.89814481  0.87892505 -1.78306677  1.11113131  0.60916656]]


In [11]:
print(np.dot(a, a.T))

[[ 0.80666409  0.78940197 -1.60145216  0.99795681  0.54711978]
 [ 0.78940197  0.77250925 -1.56718206  0.97660114  0.53541175]
 [-1.60145216 -1.56718206  3.17932712 -1.98122131 -1.08618465]
 [ 0.99795681  0.97660114 -1.98122131  1.23461278  0.67686403]
 [ 0.54711978  0.53541175 -1.08618465  0.67686403  0.37108389]]


In [12]:
print(np.dot(a.T, a))

[[ 6.36419714]]
